networks:
  net:
    driver: bridge

services:
  app:
    image: phishbowl/app:latest
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    env_file: ./app/.env
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - net

  api:
    image: phishbowl/api:latest
    build:
      context: ./api
    volumes:
      - ./api:/app
    env_file: ./api/.env
    environment:
      - ANONYMIZED_TELEMETRY=TRUE
    depends_on:
      chromadb:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - net

  chromadb:
    image: phishbowl/chromadb:latest
    build:
      context: ./chromadb
    volumes:
      - chroma-data:/chroma/chroma_data
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma_data
      - ANONYMIZED_TELEMETRY=TRUE
    ports:
      - "5000:5000"
    networks:
      - net

  nginx-dev:
    image: phishbowl/nginx:latest
    build:
      context: ./nginx-dev
      dockerfile: Dockerfile.dev
    depends_on:
      app:
        condition: service_started
      api:
        condition: service_started
    ports:
      - "80:80"
    networks:
      - net

volumes:
  chroma-data:
    driver: local