on:
  push:
    branches:
      - main
      - gh-actions
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'api/**/*.py'

  test-api:
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Clear up spaces
        run: rm -rf /opt/hostedtoolcache

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker container
        run: docker buildx build
          -t phishbowl/api:latest
          --cache-to type=gha
          --cache-from type=gha,mode=max

      - name: Create api env file
        run: |
          cd api
          touch .env
          echo env="prod" >> .env
          echo AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }} >> .env
          echo AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }} >> .env

      - name: Create app env file
        run: |
          cd app
          touch .env

      - name: Start Docker container
        run: docker compose up -d api chromadb

      - name: Run API tests
        run: docker exec -t api pytest tests


