on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Create env file
        run: |
          cd api
          touch .env
          echo env="prod" >> .env
          echo AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }} >> .env
          echo AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }} >> .env

      - name: "Setup dependencies"
        run: |
          pip install -r api/requirements.txt
          pip install pytest-dotenv==0.5.2

      - name: Test API
        run: |
          cd api
          python -m pytest tests --envfile .env
